# -*- coding: utf-8 -*-
"""Deployment of Tomato Leaf Disease model on Streamlit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F3GJ3m7DoBYzETpD_Gflfk5FwHOeFVbg
"""

!pip install streamlit

!pip install pyngrok==4.1.1

# Commented out IPython magic to ensure Python compatibility.
# %%writefile tomatto_leaf.py
# import streamlit as st
# from PIL import Image, ImageOps
# import numpy as np
# import tensorflow as tf
# 
# @st.cache(allow_output_mutation= True)
# 
# ##Load the model
# def load_model():
#   model = tf.keras.models.load_model("/content/drive/MyDrive/Tomatto-Leaf-Disease/tomatto_model_inception.h5")
#   return model
# 
# model = load_model()
# st.write("# Tomatto Leaf Disease Classification")
# 
# file = st.file_uploader('Please upload a Tomatto Leaf Image', type = ['png', 'jpg', 'jpeg'])
# 
# def import_and_model(image_data, model):
#   size = (224, 224)
#   image = ImageOps.fit(image_data, size, Image.ANTIALIAS)
#   img = np.asarray(image)
#   img = img/255.0
#   img_reshape = img[np.newaxis,...]
#   prediction = model.predict(img_reshape)
# 
#   return prediction
# 
# if file is None:
#   st.text("Please upload an image file...")
# 
# else:
#   image = Image.open(file)
#   st.image(image, use_column_width= True)
#   predictions = import_and_model(image, model)
# 
#   class_names = ['Tomato__Bacterial_spot', 'Tomato__Early_blight', 'Tomato__Late_blight', 'Tomato__Leaf_Mold', 'Tomato__Septoria_leaf_spot', 
#                  'Tomato__TwoSpotted_Spider_mites', 'Tomato_Target_Spot', 'Tomato_Yellow_Leaf_Curl_Virus',  'Tomato_Tomato_mosaic_virus','Tomato__healthy']
#   
#   preds = np.argmax(predictions, axis = 1)
#   
#   if preds == 0:
#     st.write("## The Disease is Tomato__Bacterial_spot")
#   elif preds == 1:
#     st.write("## The Disease is Tomato__Early_blight")
#   elif preds == 2:
#     st.write("## The Disease is Tomato__Late_blight")
#   elif preds == 3:
#     st.write("## The Disease is Tomato_Leaf_Mold")
#   elif preds == 4:
#     st.write("## The Disease is Tomato_Septoria_leaf_spot")
#   elif preds == 5:
#     st.write("## The Disease is Tomato__TwoSpotted_Spider_mites")
#   elif preds == 6:
#     st.write("## The Disease is Tomato_Target_Spot")
#   elif preds == 7:
#     st.write("## The Disease is Tomato_Yellow_Leaf_Curl_Virus")
#   elif preds == 8:
#     st.write("## The Disease is Tomato_mosaic_virus")
#   else:
#     st.write("## The Disease is Tomato_healthy")
# 
#

!ngrok authtoken XXXXXXXXXXXXXXXXXXXXXXXXX

!nohup streamlit run tomatto_leaf.py &

from pyngrok import ngrok

public_url = ngrok.connect(port = '8501')

public_url

ngrok.kill()



















